pipeline {
    agent any
     
    tools { 
        maven 'myMaven' 
        jdk 'myJava' 
       
      

    }
    stages {
        stage('Build Application') {
            steps {
                bat 'mvn -f java-tomcat-sample-docker/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                bat "cd"
                bat "dir"
      
                bat "docker build -f java-tomcat-sample-docker/Dockerfile -t tomcatsamplewebapp:latest"
            }
        }

    }
}
